{% set name = "node2vec" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a86de3b49d5428eafc3eb46abb0872bf5e5a1ac390dfc01fe6a90fa9030aaaff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - gensim
    - numpy
    - tqdm
    - joblib

test:
  imports:
    - node2vec
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/eliorc/node2vec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The node2vec algorithm learns continuous representations for nodes in any (un)directed, (un)weighted graph.

  description: |
    The node2vec algorithm learns continuous representations for nodes in any (un)directed, (un)weighted graph.
  doc_url: http://snap.stanford.edu/node2vec/
  dev_url: https://github.com/eliorc/node2vec

extra:
  recipe-maintainers:
    - cu8blank
