{% set name = "node2vec" %}
{% set version = "0.1.3" %}
{% set sha256 = "513ba85d774069c5423f8207ec81535e0ea6c51e52d925e82b19f7cb38568178" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx
    - gensim
    - numpy
    - tqdm
    - joblib

test:
  imports:
    - node2vec

about:
  home: https://github.com/eliorc/node2vec
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'The node2vec algorithm learns continuous representations for nodes in any (un)directed, (un)weighted graph.'

  description: |
    The node2vec algorithm learns continuous representations for nodes in any (un)directed, (un)weighted graph.
  doc_url: http://snap.stanford.edu/node2vec/
  dev_url: https://github.com/eliorc/node2vec

extra:
  recipe-maintainers:
    - cu8blank
